
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000/api
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - avp-network

networks:
  avp-network:
    external: true
    name: avp-network

